module.exports = {
  ru: "rus.",
  en: "eng.",
  city: "City: ", 
  country: "; Country: ",
  todaysDate: "Today's date: ", 
  currentWeather: "Current weather: ",
  currentTemperatureC: "Current temperature (°C): ",
  currentTemperatureF: "Current temperature (°F): ",
  generalDescription: "General description: ",
  apparentTemperatureC: "Apparent temperature (°C): ",
  apparentTemperatureF: "Apparent temperature (°F): ",
  windSpeed_ms: "Wind speed (m/s): ",
  humidity: "Humidity: ",
  F:"°F",
  C: "°C",
  WeatherForToday: "Weather for today",
  WeatherForThreeDays: "Weather for three days",
  latitude: "Latitude: ",
  longitude: "Longitude: ",
  weekDay: "Day of week: ",
  degree: "°",
  changeBack: 'change background',
};
