module.exports = {
  ru: "рус.",
  en: "англ.",
  city: "Город: ", 
  country: "; Страна: ",
  todaysDate: "Сегодняшняя дата: ", 
  currentWeather: "Погода сегодня: ",
  currentTemperatureC: "Температура (°C): ",
  currentTemperatureF: "Температура (°F): ",
  generalDescription: "Описание погоды: ",
  apparentTemperatureC: "Ощущаемся температура (°C): ",
  apparentTemperatureF: "Ощущаемся температура (°F): ",
  windSpeed_ms: "Скорость ветра (м/с): ",
  humidity: "Влажность: ",
  F:"°F",
  C: "°C",
  WeatherForToday: "Погода на сегодня",
  WeatherForThreeDays: "Погода на три дня",
  latitude: "Широта: ",
  longitude: "Долгота: ",
  weekDay: "День недели: ",
  degree: "°",
  changeBack: 'изменить фон',
};
